### PR TITLE
Sitemap product types

### LINKED ISSUE #141: [FR] Support commerce products, variants in sitemap settings
Unless I'm missing something, is doesn't seem to allow the ability to manage products and variants in the sitemap settings.

### PR DESCRIPTION
**Pull request by boboldehampsink**
Fixes #141

Changes proposed in this pull request:

Added support for commerce products in sitemap

### CODE REVIEW

**Comment by boboldehampsink** [comment]
Bump

**Comment by boboldehampsink** [comment]
cc @Tam

**Comment by boboldehampsink** [comment]
Hello, please appreciate free open-source contributions. Sincerely.

**Comment by boboldehampsink** [comment]
@Tam please consider this for release. It is an exact port of the Craft 2 version of this plugin. I am using it in production on multiple sites.

**Comment by niektenhoopen** [comment]
@jamesedmonston Are you maybe able to merge this for @boboldehampsink ? 

I might need to create a PR this week as well to fix #325. What is the best way (/ your preferred way) to keep this plugin maintained, Team Ether?

**Pull request merged**
