### PR TITLE
Add gql field-type definition for Craft 3.3 GraphQL implementation

### LINKED ISSUE #251: Just a typo
image

Should read "Optimisation Checklist"

### LINKED ISSUE #255: Support for GraphQL and headless mode?
Any plans to add support for the new GraphQL and headless modes? What would be needed to get the focus keywords to run in headless?

### PR DESCRIPTION
**Pull request by FreekVR**
Fixes #255   .

Changes proposed in this pull request:

- Adds new types for all the different objects in the SEO plugin
- Registers the types with the Craft gql registry

Note: This needs some further testing before it can be considered stable. We're currently using this fork in one of our projects, but would appreciate some further help :)

### CODE REVIEW

**Comment by jamesedmonston** [comment]
@FreekVR Thanks for this! I'm currently testing it on one of our builds using Next.js and Apollo Client; it seems to be working great.

Are there any specific use-cases you haven't tested, and would like us to?

**Comment by FreekVR** [comment]
I haven't been able to test it with keywords, as those don't work in Craft headless mode. Otherwise I've just tested this with some limited dummy data, so any testing in an application that perhaps already has a bunch of entries with different combinations of SEO data would be great :)

**Comment by jamesedmonston** [comment]
@FreekVR Awesome, good to know. This site has a fair few entries so will be able to test fairly extensively over the next couple days

**Comment by FreekVR** [comment]
Hey @jamesedmonston ,

Have you been able to do testing on your end? The project we're using this fork on internally has gone through quite some testing and we haven't found any issues yet, so it'd be great to get this PR in as far as I'm concerned :)

**Comment by magicspon** [comment]
Any news on this getting merged?

**Comment by tomfrew** [comment]
Hey @jamesedmonston,

Have been trying this branch on a project and ran into issues with Gatsby not handling the backslashes in the type names.
Probably best to swap the back slashes for underscore to bring them inline with the core craft typenames?

**Comment by FreekVR** [comment]
@tomfrew we were having the same issue and fixed those in our fork (also included in PR), if you use the fork and update it, it should work now :)

**Comment by jamesedmonston** [comment]
@Tam can we get this merged, please?

**Review by jamesedmonston — APPROVED** [review]

**Comment by bzin** [comment]
Is this going to be merged and released soon @FreekVR @jamesedmonston ? :)

**Comment by jamesedmonston** [comment]
@FreekVR we've just merged this in and released `3.6.6`. Sorry for the delay and thanks for your contribution 👍🏻

**Pull request merged**
