### PR TITLE
Fix SEO field focus keywords on Craft 4.

### LINKED ISSUE #407: Focus keywords are wiped after upgrading to 4.0.0 and can't save new ones
### Description
Hello,

I would like to mention that after updating plugin to v4.0.0 all focus keywords are wiped and you cannot add new ones. When providing a new keyword in the field, on enter it saves the entry but the keyword is not saved. 

The only related issue I could find was [Keywords in headless mode](https://github.com/ethercreative/seo/issues/372) but I am not using Craft in headless mode, so I assume keywords should work.

I'd appreciate any feedback on this issue! Thanks

### Steps to reproduce

1. Create an entry OR edit an existing one
2. Go to your SEO field, Optimisation tab
3. Provide a keyword
4. Click enter
5. Entry saved
6. Go back to the SEO field, Optimisation tab
7. No keyword saved, empty field

### Additional info

- Craft version: 4.0.2 (pro)
- SEO version: 4.0.0
- PHP version: 8.1
- Database driver & version: MYSQL 5.7.38
- Other Plugins:

### LINKED ISSUE #431: Focus keywords fields not working
### Description
When entering a focus keyword and pressing 'Enter', the page redirects to the entries listing.

### Steps to reproduce

1. Go to the edit screen of an entry
2. Type a word in the focus keywords input field
3. Press enter

### Additional info

- Craft version: Craft Pro 4.2.4 (used in dev and staging so far)
- SEO version: v4.0.3
- PHP version: 8.0.8
- Database driver & version: MySQL 5.7.34
- Other Plugins: Redactor (3.0.2), Super Table (3.0.1)

### PR DESCRIPTION
**Pull request by dyerc**
Fixes #431 and fixes #407 .

I thought I would investigate the issue with the focus keywords section on Craft version 4 and attempt to figure out what's happening. As far as I can tell, it's related to a change with the drafts / elements editor in Craft 4 and using the approach recommended in [a similar thread](https://github.com/craftcms/docs/issues/346), the focus keywords section appears to be working.

The override of `window.Craft.ElementEditor.prototype.init` in `SeoField.js` feels like a very poor solution, but I needed to ensure this code runs after the Craft ElementEditor is fully initialized.

After limited testing it appears to fix the focus keywords section, but if anybody wants to test this works, please have a try using the fork in your `composer.json`.

### CODE REVIEW

**Comment by kevinmu17** [comment]
For testers: composer.json
```js
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/dyerc/seo"
    }
  ],
  "require": {
    "ether/seo": "dev-bugfix-keywords",
  }
```
run composer update

**Comment by dyerc** [comment]
> what to put in the composer.json?

If you reference my repository in `composer.json`:

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/dyerc/seo"
        }
    ]
```

Then run:

```
composer require ether/seo:dev-bugfix-keywords
```

**Comment by kevinmu17** [comment]
This fixed the issue, thanks! hope ether will merge very soon!

**Comment by dennis-vdw** [comment]
Thanks @dyerc , this fixed the issue!

**Pull request merged**
