### PR TITLE
fix: regression on multisite canonical URLs (v4)

### LINKED ISSUE #469: Problem with canonical
### Description
Since the last update there were problems with canonical headers. On multisites with languages ​​in the subdirectory the canons appear as "https://www.mywebsites.com/en/en/about-us". sometimes even the folder was repeated three times.

### Steps to reproduce

1.Update craft to the latest versione
2.Update SEO to the latest version

### Additional info

- Craft version:4.8.0
- SEO version:4.2.2
- PHP version:8.1

### PR DESCRIPTION
**Pull request by therealpecus**
Fixes #469.

Changes proposed in this pull request:

- fixes an issue introduced with 4.2.2 on multisite installations where the language prefix in canonical URLs was repeated

This PR applies to v4 of the plugin.

### CODE REVIEW

**Comment by niektenhoopen** [comment]
@Tam Would you be able to have a look at this? The canonicals are now incorrect on all 4.2.2 installations.

**Comment by niektenhoopen** [comment]
@Tam Any updates????

**Comment by MytiX** [comment]
@Tam Could you please provide us with information about a possible future merge of the pull request ?
@therealpecus This works perfectly 👍🏻

**Comment by Tam** [comment]
Thanks!

**Pull request merged**
